# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Drost Development
email: ryan@drostdev.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance Web Developer - Husband &amp; Father
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.drostdev.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: ryansdrost
github_username:  drosty
#facebook_username: ryan.s.drost
#instagram_username: beyonce
stackoverflow_url: https://stackoverflow.com/users/506845/ryan-drost
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/ryan-drost/

# Address information
# address_street: 3034 Melrose Place
address_city: Minneapolis
address_state: MN
address_zip: 55434

# Build settings
markdown: kramdown

sass:
    style: compressed
